#pragma once

enum {
    NAVIGATION_SERVICE_UUID16 = 0xFFF0,
    NAVIGATION_CHARACTERISTIC_UUID16 = 0xFF01,
    OBD_CHARACTERISTIC_UUID16 = 0xFF02,
    BLE_ATT_DEFAULT_MTU = 23,
    BLE_ATT_WRITE_OVERHEAD = 3,
    BLE_ATT_DEFAULT_PAYLOAD_MAX = BLE_ATT_DEFAULT_MTU - BLE_ATT_WRITE_OVERHEAD,
    NAVIGATION_CHARACTERISTIC_PAYLOAD_MAX = 40,
    OBD_CHARACTERISTIC_PAYLOAD_MAX = 8,
};
